Solution/Alphabetize Me/AlphabetizeMe.WebApplication/Models/ErrorViewModel.cs
namespace AlphabetizeMe.WebApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Solution/Alphabetize Me/AlphabetizeMe.WebApplication/Controllers/AlphabetizeMeController.cs
using AlphabetizeMe.ClassLibrary;
using Microsoft.AspNetCore.Mvc;

namespace AlphabetizeMe.WebApplication.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class AlphabetizeMeController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<AlphabetizeMeController> _logger;

        public AlphabetizeMeController(ILogger<AlphabetizeMeController> logger)
        {
            _logger = logger;
        }

        [HttpGet(Name = "GetList")]
        public IEnumerable<ListData> Get()
        {
            return Enumerable.Range(1, Summaries.Length).Select(index => new ListData
            {
                Name = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }

        [HttpPost(Name = "PostSpeechSynthesis")]
        public IEnumerable<string> Post(string input)
        {
            AlphabetizeMeApp myApp = new AlphabetizeMeApp();
            bool inputAlright = myApp.CheckUserInput(input);
            List<string> myList = new List<string>();
            myList = myApp.ConvertStreamToList(input, "\r\n");
            return myList = myApp.AlphabetizeMe(myList);
        }
    }
}

Solution/Alphabetize Me/AlphabetizeMe.WebApplication/Controllers/SiteController.cs
using System.Diagnostics;
using AlphabetizeMe.ClassLibrary;
using AlphabetizeMe.WebApplication.Models;
using Microsoft.AspNetCore.Mvc;

namespace AlphabetizeMe.WebApplication.Controllers
{
    public class SiteController : Controller
    {
        private readonly ILogger<SiteController> _logger;

        public SiteController(ILogger<SiteController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            string formProcessed = Request.Query["btnSubmit"];

            if (formProcessed != null && formProcessed.ToLower() == "alphabetize")
            {
                string inputText = Request.Query["txtInput"]; inputText.Trim();

                AlphabetizeMeApp myApp = new AlphabetizeMeApp();
                if (myApp.CheckUserInput(inputText))
                {
                    List<string> myList = new List<string>();
                    myList = myApp.ConvertStreamToList(inputText, "\r\n");
                    myList = myApp.AlphabetizeMe(myList);
                    foreach (string item in myList)
                    {
                        ViewBag.InputText = ViewBag.InputText + item + "\n";
                    }
                }
            }
            
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Solution/Alphabetize Me/AlphabetizeMe.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Alphabetize Me</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AlphabetizeMe.WebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Site" asp-action="Index">Alphabetize Me</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Site" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; <span id="year"></span> Alphabetize Me - All rights reserved.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Solution/Alphabetize Me/AlphabetizeMe.WebApplication/Views/Site/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Alphabetize Me!</h1>
    <p>A small utility for securely alphabetizing a list of data values.</p>
</div>

<p>
    <form id="frmAlphabetizeMe" name="frmAlphabetizeMe" action="/" method="get">
        <p>
            <label for="txtInput">List to Alphabetize:</label><br />
            <textarea id="txtInput" name="txtInput" rows="10" cols="70">@ViewBag.InputText</textarea>
        </p>
        <p>
            <input type="submit" id="btnSubmit" name="btnSubmit" value="Alphabetize" />
            <input type="reset" id="btnReset" name="btnReset" value="Start Again" onclick="startAgain();" />
            <input type="button" id="btnCopy" name="btnCopy" value="Copy" onclick="copyTextToClipboard();" />
            <input type="button" id="btnPaste" name="btnPaste" value="Paste" onclick="pasteTextFromClipboard();" />
        </p>
    </form>
</p>